name: tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test_all:
    name: Run samplesheet conversion tests
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nvnieuwk/nf-samplesheet-conversion') }}"
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "latest-everything"

      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge,bioconda,defaults
          python-version: 3.10

      - name: Install nf-test
        run: |
          conda install -c bioconda nf-test

      - name: Run pipeline with test data
        run: |
          $CONDA/bin/nf-test test --junitxml=default.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: "default.xml"